### ISSUE TITLE
Card Modder Plugin Depreciated

### ISSUE THREAD

**Issue by michaellunzer** [mcfrojd/hassio_lovelace_multiremote#2]
Hi @mcfrojd, Great job on this! I've been using it for a while now and I noticed that [card modder](https://github.com/thomasloven/lovelace-card-modder) is depreciated now. I'm having trouble reinstalling the plugin with HACS now because the Card Modder repo is read-only. I could manually install but I figure it is probably better to use current plugins.

Can you confirm if we are able to migrate to Card-Mod? Please let me know if you are open to pull requests and maybe we can work on something together.

**Comment by mcfrojd** [comment]
Yes i have noticed this, im working on a new version that is using "custom button card" instead.
I was not able to make an easy migrate to card-mod, but the button card seems to work good.
Might publish a smaller example in a near future.

**Comment by mcfrojd** [comment]
Update complete.
